database:
  url: "jdbc:mysql://localhost:3306/skycloud?characterEncoding=utf8"
  table: "skychat_users"
  username: "admin"
  password: "admin2"

utils:
  staffPermission: 'skycloud.staff'
  staffColor: '&4'

chat:
  defaultBio: "&eHey! I'm the default bio value text"
  format: "%luckperms_prefix%{playerName}: &f{content}"
  hover: |-
    &c&lBio
     &e{playerBio}
    
    &7(Click to message %player_name%)